// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod raft {
    pub mod consensus {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum NodeState {
                Follower,
                Candidate,
                Leader,
                Dead,
            }
            impl ::core::fmt::Debug for NodeState {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        NodeState::Follower => {
                            f.debug_tuple("NodeState::Follower").finish()
                        }
                        NodeState::Candidate => {
                            f.debug_tuple("NodeState::Candidate").finish()
                        }
                        NodeState::Leader => f.debug_tuple("NodeState::Leader").finish(),
                        NodeState::Dead => f.debug_tuple("NodeState::Dead").finish(),
                    }
                }
            }
            impl NodeState {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> NodeState {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => NodeState::Follower,
                        1 => NodeState::Candidate,
                        2 => NodeState::Leader,
                        3 => NodeState::Dead,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct PreVoteRequest {
                pub term: u64,
                pub candidate_id: u64,
                pub last_log_index: u64,
                pub last_log_term: u64,
            }
            impl ::core::fmt::Debug for PreVoteRequest {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("PreVoteRequest")
                        .field("term", &self.term)
                        .field("candidate-id", &self.candidate_id)
                        .field("last-log-index", &self.last_log_index)
                        .field("last-log-term", &self.last_log_term)
                        .finish()
                }
            }
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct PreVoteResponse {
                pub term: u64,
                pub vote_granted: bool,
            }
            impl ::core::fmt::Debug for PreVoteResponse {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("PreVoteResponse")
                        .field("term", &self.term)
                        .field("vote-granted", &self.vote_granted)
                        .finish()
                }
            }
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct VoteRequest {
                pub term: u64,
                pub candidate_id: u64,
                pub last_log_index: u64,
                pub last_log_term: u64,
            }
            impl ::core::fmt::Debug for VoteRequest {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("VoteRequest")
                        .field("term", &self.term)
                        .field("candidate-id", &self.candidate_id)
                        .field("last-log-index", &self.last_log_index)
                        .field("last-log-term", &self.last_log_term)
                        .finish()
                }
            }
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct VoteResponse {
                pub term: u64,
                pub vote_granted: bool,
            }
            impl ::core::fmt::Debug for VoteResponse {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("VoteResponse")
                        .field("term", &self.term)
                        .field("vote-granted", &self.vote_granted)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct LogEntry {
                pub term: u64,
                pub index: u64,
                pub command: _rt::Vec<u8>,
            }
            impl ::core::fmt::Debug for LogEntry {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("LogEntry")
                        .field("term", &self.term)
                        .field("index", &self.index)
                        .field("command", &self.command)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct AppendEntries {
                pub term: u64,
                pub leader_id: u64,
                pub prev_log_index: u64,
                pub prev_log_term: u64,
                pub entries: _rt::Vec<LogEntry>,
                pub leader_commit: u64,
            }
            impl ::core::fmt::Debug for AppendEntries {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("AppendEntries")
                        .field("term", &self.term)
                        .field("leader-id", &self.leader_id)
                        .field("prev-log-index", &self.prev_log_index)
                        .field("prev-log-term", &self.prev_log_term)
                        .field("entries", &self.entries)
                        .field("leader-commit", &self.leader_commit)
                        .finish()
                }
            }
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct AppendEntriesResponse {
                pub term: u64,
                pub success: bool,
            }
            impl ::core::fmt::Debug for AppendEntriesResponse {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("AppendEntriesResponse")
                        .field("term", &self.term)
                        .field("success", &self.success)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub enum RaftMessage {
                PreVoteReq(PreVoteRequest),
                PreVoteRes(PreVoteResponse),
                VoteReq(VoteRequest),
                VoteRes(VoteResponse),
                AppendReq(AppendEntries),
                AppendRes(AppendEntriesResponse),
            }
            impl ::core::fmt::Debug for RaftMessage {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        RaftMessage::PreVoteReq(e) => {
                            f.debug_tuple("RaftMessage::PreVoteReq").field(e).finish()
                        }
                        RaftMessage::PreVoteRes(e) => {
                            f.debug_tuple("RaftMessage::PreVoteRes").field(e).finish()
                        }
                        RaftMessage::VoteReq(e) => {
                            f.debug_tuple("RaftMessage::VoteReq").field(e).finish()
                        }
                        RaftMessage::VoteRes(e) => {
                            f.debug_tuple("RaftMessage::VoteRes").field(e).finish()
                        }
                        RaftMessage::AppendReq(e) => {
                            f.debug_tuple("RaftMessage::AppendReq").field(e).finish()
                        }
                        RaftMessage::AppendRes(e) => {
                            f.debug_tuple("RaftMessage::AppendRes").field(e).finish()
                        }
                    }
                }
            }
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct NodeStatus {
                pub id: u64,
                pub state: NodeState,
                pub term: u64,
                pub log_length: u64,
                pub commit_index: u64,
            }
            impl ::core::fmt::Debug for NodeStatus {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("NodeStatus")
                        .field("id", &self.id)
                        .field("state", &self.state)
                        .field("term", &self.term)
                        .field("log-length", &self.log_length)
                        .field("commit-index", &self.commit_index)
                        .finish()
                }
            }
        }
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod host {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type RaftMessage = super::super::super::raft::consensus::types::RaftMessage;
            pub type LogEntry = super::super::super::raft::consensus::types::LogEntry;
            #[allow(unused_unsafe, clippy::all)]
            pub fn send_message(to_node: u64, msg: &RaftMessage) -> () {
                unsafe {
                    let mut cleanup_list = _rt::Vec::new();
                    use super::super::super::raft::consensus::types::RaftMessage as V9;
                    let (
                        result10_0,
                        result10_1,
                        result10_2,
                        result10_3,
                        result10_4,
                        result10_5,
                        result10_6,
                        result10_7,
                    ) = match msg {
                        V9::PreVoteReq(e) => {
                            let super::super::super::raft::consensus::types::PreVoteRequest {
                                term: term0,
                                candidate_id: candidate_id0,
                                last_log_index: last_log_index0,
                                last_log_term: last_log_term0,
                            } = e;
                            (
                                0i32,
                                _rt::as_i64(term0),
                                _rt::as_i64(candidate_id0),
                                _rt::as_i64(last_log_index0),
                                _rt::as_i64(last_log_term0),
                                ::core::ptr::null_mut(),
                                0usize,
                                0i64,
                            )
                        }
                        V9::PreVoteRes(e) => {
                            let super::super::super::raft::consensus::types::PreVoteResponse {
                                term: term1,
                                vote_granted: vote_granted1,
                            } = e;
                            (
                                1i32,
                                _rt::as_i64(term1),
                                i64::from(
                                    match vote_granted1 {
                                        true => 1,
                                        false => 0,
                                    },
                                ),
                                0i64,
                                0i64,
                                ::core::ptr::null_mut(),
                                0usize,
                                0i64,
                            )
                        }
                        V9::VoteReq(e) => {
                            let super::super::super::raft::consensus::types::VoteRequest {
                                term: term2,
                                candidate_id: candidate_id2,
                                last_log_index: last_log_index2,
                                last_log_term: last_log_term2,
                            } = e;
                            (
                                2i32,
                                _rt::as_i64(term2),
                                _rt::as_i64(candidate_id2),
                                _rt::as_i64(last_log_index2),
                                _rt::as_i64(last_log_term2),
                                ::core::ptr::null_mut(),
                                0usize,
                                0i64,
                            )
                        }
                        V9::VoteRes(e) => {
                            let super::super::super::raft::consensus::types::VoteResponse {
                                term: term3,
                                vote_granted: vote_granted3,
                            } = e;
                            (
                                3i32,
                                _rt::as_i64(term3),
                                i64::from(
                                    match vote_granted3 {
                                        true => 1,
                                        false => 0,
                                    },
                                ),
                                0i64,
                                0i64,
                                ::core::ptr::null_mut(),
                                0usize,
                                0i64,
                            )
                        }
                        V9::AppendReq(e) => {
                            let super::super::super::raft::consensus::types::AppendEntries {
                                term: term4,
                                leader_id: leader_id4,
                                prev_log_index: prev_log_index4,
                                prev_log_term: prev_log_term4,
                                entries: entries4,
                                leader_commit: leader_commit4,
                            } = e;
                            let vec7 = entries4;
                            let len7 = vec7.len();
                            let layout7 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec7.len() * (16 + 2 * ::core::mem::size_of::<*const u8>()),
                                8,
                            );
                            let result7 = if layout7.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout7).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout7);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec7.into_iter().enumerate() {
                                let base = result7
                                    .add(i * (16 + 2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let super::super::super::raft::consensus::types::LogEntry {
                                        term: term5,
                                        index: index5,
                                        command: command5,
                                    } = e;
                                    *base.add(0).cast::<i64>() = _rt::as_i64(term5);
                                    *base.add(8).cast::<i64>() = _rt::as_i64(index5);
                                    let vec6 = command5;
                                    let ptr6 = vec6.as_ptr().cast::<u8>();
                                    let len6 = vec6.len();
                                    *base
                                        .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len6;
                                    *base.add(16).cast::<*mut u8>() = ptr6.cast_mut();
                                }
                            }
                            cleanup_list.extend_from_slice(&[(result7, layout7)]);
                            (
                                4i32,
                                _rt::as_i64(term4),
                                _rt::as_i64(leader_id4),
                                _rt::as_i64(prev_log_index4),
                                _rt::as_i64(prev_log_term4),
                                result7,
                                len7,
                                _rt::as_i64(leader_commit4),
                            )
                        }
                        V9::AppendRes(e) => {
                            let super::super::super::raft::consensus::types::AppendEntriesResponse {
                                term: term8,
                                success: success8,
                            } = e;
                            (
                                5i32,
                                _rt::as_i64(term8),
                                i64::from(
                                    match success8 {
                                        true => 1,
                                        false => 0,
                                    },
                                ),
                                0i64,
                                0i64,
                                ::core::ptr::null_mut(),
                                0usize,
                                0i64,
                            )
                        }
                    };
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "raft:consensus/host")]
                    unsafe extern "C" {
                        #[link_name = "send-message"]
                        fn wit_import11(
                            _: i64,
                            _: i32,
                            _: i64,
                            _: i64,
                            _: i64,
                            _: i64,
                            _: *mut u8,
                            _: usize,
                            _: i64,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import11(
                        _: i64,
                        _: i32,
                        _: i64,
                        _: i64,
                        _: i64,
                        _: i64,
                        _: *mut u8,
                        _: usize,
                        _: i64,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import11(
                            _rt::as_i64(&to_node),
                            result10_0,
                            result10_1,
                            result10_2,
                            result10_3,
                            result10_4,
                            result10_5,
                            result10_6,
                            result10_7,
                        )
                    };
                    for (ptr, layout) in cleanup_list {
                        if layout.size() != 0 {
                            _rt::alloc::dealloc(ptr.cast(), layout);
                        }
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn persist_state(term: u64, voted_for: Option<u64>) -> () {
                unsafe {
                    let (result0_0, result0_1) = match voted_for {
                        Some(e) => (1i32, _rt::as_i64(e)),
                        None => (0i32, 0i64),
                    };
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "raft:consensus/host")]
                    unsafe extern "C" {
                        #[link_name = "persist-state"]
                        fn wit_import1(_: i64, _: i32, _: i64);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: i64, _: i32, _: i64) {
                        unreachable!()
                    }
                    unsafe { wit_import1(_rt::as_i64(&term), result0_0, result0_1) };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn persist_log(entries: &[LogEntry]) -> () {
                unsafe {
                    let vec2 = entries;
                    let len2 = vec2.len();
                    let layout2 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec2.len() * (16 + 2 * ::core::mem::size_of::<*const u8>()),
                        8,
                    );
                    let result2 = if layout2.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout2).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout2);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec2.into_iter().enumerate() {
                        let base = result2
                            .add(i * (16 + 2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let super::super::super::raft::consensus::types::LogEntry {
                                term: term0,
                                index: index0,
                                command: command0,
                            } = e;
                            *base.add(0).cast::<i64>() = _rt::as_i64(term0);
                            *base.add(8).cast::<i64>() = _rt::as_i64(index0);
                            let vec1 = command0;
                            let ptr1 = vec1.as_ptr().cast::<u8>();
                            let len1 = vec1.len();
                            *base
                                .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len1;
                            *base.add(16).cast::<*mut u8>() = ptr1.cast_mut();
                        }
                    }
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "raft:consensus/host")]
                    unsafe extern "C" {
                        #[link_name = "persist-log"]
                        fn wit_import3(_: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import3(_: *mut u8, _: usize) {
                        unreachable!()
                    }
                    unsafe { wit_import3(result2, len2) };
                    if layout2.size() != 0 {
                        _rt::alloc::dealloc(result2.cast(), layout2);
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn now_ms() -> u64 {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "raft:consensus/host")]
                    unsafe extern "C" {
                        #[link_name = "now-ms"]
                        fn wit_import0() -> i64;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0() -> i64 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0() };
                    ret as u64
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn random_timeout(min_ms: u64, max_ms: u64) -> u64 {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "raft:consensus/host")]
                    unsafe extern "C" {
                        #[link_name = "random-timeout"]
                        fn wit_import0(_: i64, _: i64) -> i64;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0(_: i64, _: i64) -> i64 {
                        unreachable!()
                    }
                    let ret = unsafe {
                        wit_import0(_rt::as_i64(&min_ms), _rt::as_i64(&max_ms))
                    };
                    ret as u64
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod raft {
        pub mod consensus {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod raft_api {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type NodeStatus = super::super::super::super::raft::consensus::types::NodeStatus;
                pub type RaftMessage = super::super::super::super::raft::consensus::types::RaftMessage;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_init_cabi<T: Guest>(
                    arg0: i64,
                    arg1: *mut u8,
                    arg2: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    T::init(
                        arg0 as u64,
                        _rt::Vec::from_raw_parts(arg1.cast(), len0, len0),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_tick_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::tick();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let super::super::super::super::raft::consensus::types::NodeStatus {
                        id: id2,
                        state: state2,
                        term: term2,
                        log_length: log_length2,
                        commit_index: commit_index2,
                    } = result0;
                    *ptr1.add(0).cast::<i64>() = _rt::as_i64(id2);
                    *ptr1.add(8).cast::<u8>() = (state2.clone() as i32) as u8;
                    *ptr1.add(16).cast::<i64>() = _rt::as_i64(term2);
                    *ptr1.add(24).cast::<i64>() = _rt::as_i64(log_length2);
                    *ptr1.add(32).cast::<i64>() = _rt::as_i64(commit_index2);
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_message_cabi<T: Guest>(
                    arg0: i64,
                    arg1: i32,
                    arg2: i64,
                    arg3: i64,
                    arg4: i64,
                    arg5: i64,
                    arg6: *mut u8,
                    arg7: usize,
                    arg8: i64,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    use super::super::super::super::raft::consensus::types::RaftMessage as V6;
                    let v6 = match arg1 {
                        0 => {
                            let e6 = super::super::super::super::raft::consensus::types::PreVoteRequest {
                                term: arg2 as u64,
                                candidate_id: arg3 as u64,
                                last_log_index: arg4 as u64,
                                last_log_term: arg5 as u64,
                            };
                            V6::PreVoteReq(e6)
                        }
                        1 => {
                            let e6 = super::super::super::super::raft::consensus::types::PreVoteResponse {
                                term: arg2 as u64,
                                vote_granted: _rt::bool_lift(arg3 as i32 as u8),
                            };
                            V6::PreVoteRes(e6)
                        }
                        2 => {
                            let e6 = super::super::super::super::raft::consensus::types::VoteRequest {
                                term: arg2 as u64,
                                candidate_id: arg3 as u64,
                                last_log_index: arg4 as u64,
                                last_log_term: arg5 as u64,
                            };
                            V6::VoteReq(e6)
                        }
                        3 => {
                            let e6 = super::super::super::super::raft::consensus::types::VoteResponse {
                                term: arg2 as u64,
                                vote_granted: _rt::bool_lift(arg3 as i32 as u8),
                            };
                            V6::VoteRes(e6)
                        }
                        4 => {
                            let e6 = {
                                let base5 = arg6;
                                let len5 = arg7;
                                let mut result5 = _rt::Vec::with_capacity(len5);
                                for i in 0..len5 {
                                    let base = base5
                                        .add(i * (16 + 2 * ::core::mem::size_of::<*const u8>()));
                                    let e5 = {
                                        let l0 = *base.add(0).cast::<i64>();
                                        let l1 = *base.add(8).cast::<i64>();
                                        let l2 = *base.add(16).cast::<*mut u8>();
                                        let l3 = *base
                                            .add(16 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len4 = l3;
                                        super::super::super::super::raft::consensus::types::LogEntry {
                                            term: l0 as u64,
                                            index: l1 as u64,
                                            command: _rt::Vec::from_raw_parts(l2.cast(), len4, len4),
                                        }
                                    };
                                    result5.push(e5);
                                }
                                _rt::cabi_dealloc(
                                    base5,
                                    len5 * (16 + 2 * ::core::mem::size_of::<*const u8>()),
                                    8,
                                );
                                super::super::super::super::raft::consensus::types::AppendEntries {
                                    term: arg2 as u64,
                                    leader_id: arg3 as u64,
                                    prev_log_index: arg4 as u64,
                                    prev_log_term: arg5 as u64,
                                    entries: result5,
                                    leader_commit: arg8 as u64,
                                }
                            };
                            V6::AppendReq(e6)
                        }
                        n => {
                            debug_assert_eq!(n, 5, "invalid enum discriminant");
                            let e6 = super::super::super::super::raft::consensus::types::AppendEntriesResponse {
                                term: arg2 as u64,
                                success: _rt::bool_lift(arg3 as i32 as u8),
                            };
                            V6::AppendRes(e6)
                        }
                    };
                    T::on_message(arg0 as u64, v6);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_submit_command_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let result1 = T::submit_command(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                    );
                    match result1 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_status_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_status();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let super::super::super::super::raft::consensus::types::NodeStatus {
                        id: id2,
                        state: state2,
                        term: term2,
                        log_length: log_length2,
                        commit_index: commit_index2,
                    } = result0;
                    *ptr1.add(0).cast::<i64>() = _rt::as_i64(id2);
                    *ptr1.add(8).cast::<u8>() = (state2.clone() as i32) as u8;
                    *ptr1.add(16).cast::<i64>() = _rt::as_i64(term2);
                    *ptr1.add(24).cast::<i64>() = _rt::as_i64(log_length2);
                    *ptr1.add(32).cast::<i64>() = _rt::as_i64(commit_index2);
                    ptr1
                }
                pub trait Guest {
                    fn init(node_id: u64, node_ids: _rt::Vec<u64>) -> ();
                    fn tick() -> NodeStatus;
                    fn on_message(from_node: u64, msg: RaftMessage) -> ();
                    fn submit_command(command: _rt::Vec<u8>) -> bool;
                    fn get_status() -> NodeStatus;
                }
                #[doc(hidden)]
                macro_rules! __export_raft_consensus_raft_api_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "raft:consensus/raft-api#init")] unsafe extern "C" fn
                        export_init(arg0 : i64, arg1 : * mut u8, arg2 : usize,) { unsafe
                        { $($path_to_types)*:: _export_init_cabi::<$ty > (arg0, arg1,
                        arg2) } } #[unsafe (export_name =
                        "raft:consensus/raft-api#tick")] unsafe extern "C" fn
                        export_tick() -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_tick_cabi::<$ty > () } } #[unsafe (export_name =
                        "raft:consensus/raft-api#on-message")] unsafe extern "C" fn
                        export_on_message(arg0 : i64, arg1 : i32, arg2 : i64, arg3 : i64,
                        arg4 : i64, arg5 : i64, arg6 : * mut u8, arg7 : usize, arg8 :
                        i64,) { unsafe { $($path_to_types)*::
                        _export_on_message_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4,
                        arg5, arg6, arg7, arg8) } } #[unsafe (export_name =
                        "raft:consensus/raft-api#submit-command")] unsafe extern "C" fn
                        export_submit_command(arg0 : * mut u8, arg1 : usize,) -> i32 {
                        unsafe { $($path_to_types)*:: _export_submit_command_cabi::<$ty >
                        (arg0, arg1) } } #[unsafe (export_name =
                        "raft:consensus/raft-api#get-status")] unsafe extern "C" fn
                        export_get_status() -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_get_status_cabi::<$ty > () } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_raft_consensus_raft_api_cabi;
                #[repr(align(8))]
                struct _RetArea([::core::mem::MaybeUninit<u8>; 40]);
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 40],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::vec::Vec;
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub use alloc_crate::alloc;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_raft_node_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::raft::consensus::raft_api::__export_raft_consensus_raft_api_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::raft::consensus::raft_api);
    };
}
#[doc(inline)]
pub(crate) use __export_raft_node_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:raft:consensus:raft-node:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1331] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xb3\x09\x01A\x02\x01\
A\x09\x01B\x16\x01m\x04\x08follower\x09candidate\x06leader\x04dead\x04\0\x0anode\
-state\x03\0\0\x01r\x04\x04termw\x0ccandidate-idw\x0elast-log-indexw\x0dlast-log\
-termw\x04\0\x10pre-vote-request\x03\0\x02\x01r\x02\x04termw\x0cvote-granted\x7f\
\x04\0\x11pre-vote-response\x03\0\x04\x01r\x04\x04termw\x0ccandidate-idw\x0elast\
-log-indexw\x0dlast-log-termw\x04\0\x0cvote-request\x03\0\x06\x01r\x02\x04termw\x0c\
vote-granted\x7f\x04\0\x0dvote-response\x03\0\x08\x01p}\x01r\x03\x04termw\x05ind\
exw\x07command\x0a\x04\0\x09log-entry\x03\0\x0b\x01p\x0c\x01r\x06\x04termw\x09le\
ader-idw\x0eprev-log-indexw\x0dprev-log-termw\x07entries\x0d\x0dleader-commitw\x04\
\0\x0eappend-entries\x03\0\x0e\x01r\x02\x04termw\x07success\x7f\x04\0\x17append-\
entries-response\x03\0\x10\x01q\x06\x0cpre-vote-req\x01\x03\0\x0cpre-vote-res\x01\
\x05\0\x08vote-req\x01\x07\0\x08vote-res\x01\x09\0\x0aappend-req\x01\x0f\0\x0aap\
pend-res\x01\x11\0\x04\0\x0craft-message\x03\0\x12\x01r\x05\x02idw\x05state\x01\x04\
termw\x0alog-lengthw\x0ccommit-indexw\x04\0\x0bnode-status\x03\0\x14\x03\0\x14ra\
ft:consensus/types\x05\0\x02\x03\0\0\x0craft-message\x02\x03\0\0\x09log-entry\x01\
B\x10\x02\x03\x02\x01\x01\x04\0\x0craft-message\x03\0\0\x02\x03\x02\x01\x02\x04\0\
\x09log-entry\x03\0\x02\x01@\x02\x07to-nodew\x03msg\x01\x01\0\x04\0\x0csend-mess\
age\x01\x04\x01kw\x01@\x02\x04termw\x09voted-for\x05\x01\0\x04\0\x0dpersist-stat\
e\x01\x06\x01p\x03\x01@\x01\x07entries\x07\x01\0\x04\0\x0bpersist-log\x01\x08\x01\
@\0\0w\x04\0\x06now-ms\x01\x09\x01@\x02\x06min-msw\x06max-msw\0w\x04\0\x0erandom\
-timeout\x01\x0a\x03\0\x13raft:consensus/host\x05\x03\x02\x03\0\0\x0bnode-status\
\x01B\x0f\x02\x03\x02\x01\x04\x04\0\x0bnode-status\x03\0\0\x02\x03\x02\x01\x01\x04\
\0\x0craft-message\x03\0\x02\x01pw\x01@\x02\x07node-idw\x08node-ids\x04\x01\0\x04\
\0\x04init\x01\x05\x01@\0\0\x01\x04\0\x04tick\x01\x06\x01@\x02\x09from-nodew\x03\
msg\x03\x01\0\x04\0\x0aon-message\x01\x07\x01p}\x01@\x01\x07command\x08\0\x7f\x04\
\0\x0esubmit-command\x01\x09\x04\0\x0aget-status\x01\x06\x04\0\x17raft:consensus\
/raft-api\x05\x05\x04\0\x18raft:consensus/raft-node\x04\0\x0b\x0f\x01\0\x09raft-\
node\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\
\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
